# SITE SETTINGS
title: Georeferencing.org
author: Georeferencing.org # Used for copyright statement in footer
# url: "https://georeferencing.org" # No slash at the end
baseurl: "/georeferencing.org"

# SOCIAL PROFILES
# social:
#   email: 
#   twitter: 
#   github: 

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.1
posts_on_home: 3
tweets_on_home: false
archive_permalink: /news/
github_edit: true
logo: assets/logos/Georef_Logo_Transparent.png
colors:
  links: "#FBA534"  # Default #84a8bd
  banner: "#7a9a8e"  # Default #96a493
  footer: "#d89c2d"  # Default #566571
font_serif: true
rounded_corners: true

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - assets/favicons/README.md
  - _posts/README.md

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: "posts"
    values:
      permalink: "/news/:year/:slug/" # Use /blog/yyyy/{filename}/ as permalink for all posts
